version: '3.8'

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile.bot
    container_name: telegram_bot
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - API_URL=${API_URL}
      - API_TOKEN=${API_TOKEN}
    restart: unless-stopped
    networks:
      - app-network

  webhook:
    build:
      context: .
      dockerfile: Dockerfile.webhook
    container_name: webhook_server
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - API_URL=${API_URL}
      - API_TOKEN=${API_TOKEN}
    ports:
      - "5000:5000"
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge